name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.head_ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo test, and deploy your project.
